version: '3.9'
services:
    php-apache:
      container_name: pequeno_proyecto_php_mvc
      build: .
      restart: always
      ports:
        - 8084:80
      volumes:
        - ./:/var/www/html/pequeno_proyecto
      networks:
        - network

networks:
  network:
    driver: bridge
