version: '3.9'
services:
    php-apache:
      container_name: Tienda
      build: .
      restart: always
      ports:
        - 8089:80
      volumes:
        - ./:/var/www/html/Tienda
      networks:
        - network

networks:
  network:
    driver: bridge
