version: '3.9'
services:
    php-apache:
      container_name: evaluacion
      build: .
      restart: always
      ports:
        - 8080:80
      volumes:
        - ./:/var/www/html/evaluacion
      networks:
        - network

networks:
  network:
    driver: bridge
